language: node_js

os:
  - linux

cache:
  directories:
  - node_modules
  - $HOME/.cache
  - $HOME/.npm

node_js:
  - "8"

before_script:
  - npm install -g bower
  - bower install

install:
    - npm install

script:
    - node app.js
