language: node_js

sudo: required

os:
  - linux

#https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications
notifications:
  email: false

cache:
  directories:
  - node_modules
  - $HOME/.cache
  - $HOME/.npm

#https://docs.travis-ci.com/user/database-setup/#MongoDB
services:
  - mongodb

#https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
node_js:
  - "8"

before_install:
  - npm install -g bower

install:
    - npm install

script:
	# ampersand means run in the background
    - node app.js &
    # wait for the app to load
    - sleep 6
    # a simple way of checking if nodejs is running?
    - curl localhost:3000
