language: node_js

sudo: required

os:
  - linux

notifications:
  email: false

cache:
  directories:
  - node_modules
  - $HOME/.cache
  - $HOME/.npm

services:
  - mongodb

node_js:
  - "8"

before_install:
  - npm install -g bower

install:
    - npm install

script:
    - node app.js &
    - sleep 6
